spring.application.name=sistema-estudantes

spring.application.version=1.0.0

spring.datasource.url=jdbc:h2:mem:ApiSpringbot

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=root

spring.datasource.password=root